Story/ccls 2181 app submission summary screen
ministryofjustice/laa-ccms-caab pull request #251
Opened 2024-08-07 13:45 UTC by PhilDigitalJustice

This task involves creating a final case submission summary screen in the CAAB-UI, which is displayed after all validation is complete. The screen will provide a detailed summary of various sections of the application, including client details, general details, provider details, proceedings and costs, opponents and other parties, means assessments, and merits assessment. The screen will also have a "Print" button (covered in another story), a "Next" button that navigates to the sign declaration screen, and a "Back" button that returns the user to the create application section screen.

As a user, 
I want to view a comprehensive summary of my application before submission, 
so that I can review all entered information for accuracy and completeness.

Design:

Client Details:

Basic Client Details
Contact Details
Address Details
Equal Opportunities Monitoring

General Details:

Correspondence Address
Provider Details

Proceedings and Costs:

Each Proceeding's Details
Each Proceeding's Scope Limitations

Opponents and Other Parties:
Individuals
Companies
Means Assessments
Merits Assessment

Technical Implementation:

Create Submission Summary Screen:
Develop the screen to display the application summary after validation is complete.
Use the provided screenshot as a reference for the layout and design.

Display Summary Information:

Fetch and display all relevant data sections:

Client Details (basic, contact, address, equal opportunities monitoring)
General Details (correspondence address)
Provider Details
Proceedings and Costs (details, scope limitations)
Opponents and Other Parties (individuals, companies)
Means Assessments
Merits Assessment

Navigation Buttons:

Implement the "Print" button (functionality covered in another story).
Implement the "Next" button to navigate to the sign declaration screen.
Implement the "Back" button to return to the create application section screen.

Data Fetching:

Ensure the necessary data is fetched and displayed correctly.
Handle any data loading states and errors appropriately.
Use asynchronous methods where possible 

Acceptance Criteria:

The submission summary screen displays all required sections accurately.
Users can review all details of their application in a clear and organised format.
The "Print" button is present (functionality to be implemented in another story).
The "Next" button navigates to the sign declaration screen.
The "Back" button returns the user to the create application section screen.
Comprehensive testing is conducted to ensure all information is displayed correctly and navigation works as intended.

2024-08-12 14:23 UTC, farrell-m requested changes
Nice job 👍  Just a few small comments

2024-08-12 14:24 UTC, PhilDigitalJustice commented on build.gradle
> +	implementation 'uk.gov.laa.ccms.soa.gateway:soa-gateway-api:0.0.26-9346235-SNAPSHOT'
Will do this using the automated pr after this is reviewed

2024-08-12 14:27 UTC, PhilDigitalJustice commented on src/main/java/uk/gov/laa/ccms/caab/service/LookupService.java
> +  public Mono<List<CommonLookupValueDetail>> addCommonLookupsToModel(
Yes you are correct, i will also adjust the other common abstract method that uses this.

2024-08-15 09:31 UTC, PhilDigitalJustice commented on src/test/java/uk/gov/laa/ccms/caab/controller/application/section/ApplicationSubmissionControllerTest.java
> +    Mockito.verify(lookupService, Mockito.times(2)).getAssessmentSummaryAttributes(any());
Amended

2024-08-15 09:31 UTC, PhilDigitalJustice commented on src/test/java/uk/gov/laa/ccms/caab/controller/application/client/ClientSummaryControllerTest.java
> +    verify(lookupService, atLeastOnce()).addCommonLookupsToModel(anyList(), any(Model.class));
Amended

2024-08-20 07:00 UTC, merged