CCMSPUI-425 | Replace all buttons with govuk dialect
ministryofjustice/laa-ccms-caab pull request #316
Opened 2024-12-11 12:55 UTC by arunkumar461

2024-12-12 10:15 UTC, farrell-m approved these changes
Looks good, just need to update the snapshot version.

2024-12-12 15:11 UTC, PhilDigitalJustice requested changes

2024-12-12 15:11 UTC, PhilDigitalJustice commented on src/main/resources/messages.properties
> +application.register=Register new client
```suggestion
client.register=Register new client
```

2024-12-12 15:11 UTC, PhilDigitalJustice commented on src/main/resources/templates/application/application-client-search-no-results.html
> +            <govuk:button type="submit" th:text="#{application.register}"/>
```suggestion
            <govuk:button type="submit" th:text="#{client.register}"/>
```

2024-12-12 15:11 UTC, PhilDigitalJustice commented on src/main/resources/templates/application/application-client-search-results.html
> +            <govuk:button type="submit" th:text="#{application.register}"/>
```suggestion
            <govuk:button type="submit" th:text="#{client.register}"/>
```

2024-12-16 11:27 UTC, PhilDigitalJustice approved these changes

2024-12-16 12:29 UTC, merged