CCMSPUI-454: Implement EBS Get Notifications Endpoint on PUI UI
ministryofjustice/laa-ccms-caab pull request #335
Opened 2024-12-19 15:13 UTC by JamieBriggs-MoJ

As part of work for CCMSPUI-454, the get notifications screen need to be refactored to utilise the EBS API instead of the SOA API following work done as part of CCMSPUI-453. 

Included in the PR is also additional validation to ensure the user cannot select a date range larger than 3 years when searching for notifications, and also the refactoring of the frontend to use the MoJ Date Picker component instead of the GOV UK date input component.

2024-12-19 20:11 UTC, arunkumar461 commented on src/main/resources/templates/notifications/actions-and-notifications-search.html
> +                For example, 17/5/2024. Notifications of up to 3 years after this date will be
nit: Could you move this text to the messages.properties file for consistency?

2024-12-19 20:11 UTC, arunkumar461 commented on src/main/resources/templates/notifications/actions-and-notifications-search.html
> +                For example, 17/5/2024. Notifications of up to 3 years before this date will be
nit: same here

2025-01-06 18:05 UTC, JamieBriggs-MoJ commented on src/main/resources/templates/notifications/actions-and-notifications-search.html
> +                For example, 17/5/2024. Notifications of up to 3 years after this date will be
Have updated to use messages.properties

2025-01-06 18:05 UTC, JamieBriggs-MoJ commented on src/main/resources/templates/notifications/actions-and-notifications-search.html
> +                For example, 17/5/2024. Notifications of up to 3 years before this date will be
Have updated to use messages.properties

2025-01-06 18:13 UTC, JamieBriggs-MoJ commented
Will still need to update `build.gradle` once [CCMSPUI-377](https://github.com/ministryofjustice/laa-ccms-soa-gateway-api/pull/153) has been merged in the SOA API.

2025-01-07 11:00 UTC, PhilDigitalJustice requested changes
Minor comments to address

2025-01-07 11:01 UTC, PhilDigitalJustice commented on src/main/java/uk/gov/laa/ccms/caab/controller/notifications/ActionsAndNotificationsController.java
> +          Document soaDocument = new Document();
Do you still need the temp comment?

2025-01-08 15:59 UTC, PhilDigitalJustice commented
Just fix checkstyle warning and rebase, the rest LGTM

2025-01-08 16:00 UTC, PhilDigitalJustice approved these changes

2025-01-08 23:42 UTC, arunkumar461 commented on src/main/java/uk/gov/laa/ccms/caab/client/EbsApiClient.java
> +    Optional.ofNullable(criteria.getCaseReference())
Nit: Just a suggestion, the use of Optional.ofNullable(something) is repeated in several places. Instead...

```
private MultiValueMap<String, String> buildQueryParams(
    final NotificationSearchCriteria criteria,
    final Integer page,
    final Integer pageSize) {

    final MultiValueMap<String, String> queryParams = new LinkedMultiValueMap<>();

    addQueryParam(queryParams, "case-reference-number", criteria.getCaseReference());
    addQueryParam(queryParams, "provider-case-reference", criteria.getProviderCaseReference());
   
    return queryParams;
}

private void addQueryParam(MultiValueMap<String, String> queryParams, String key, Object value) {
    Optional.ofNullable(value)
        .ifPresent(v -> queryParams.add(key, String.valueOf(v)));
}

```

2025-01-08 23:42 UTC, arunkumar461 commented on build.gradle
> +	implementation 'uk.gov.laa.ccms.data:data-api:0.0.27-398d49f-SNAPSHOT'
Nit: For sure you will change.

2025-01-08 23:42 UTC, arunkumar461 commented on src/main/resources/templates/notifications/actions-and-notifications-search.html
> +      <span class="govuk-caption-l" th:text="#{client.notifications.search.subHeading}">Search for notifications</span>
nit: Do we need these additional texts? `Search for notifications`

2025-01-09 11:48 UTC, farrell-m approved these changes

2025-01-09 13:20 UTC, JamieBriggs-MoJ commented on src/main/java/uk/gov/laa/ccms/caab/client/EbsApiClient.java
> +    Optional.ofNullable(criteria.getCaseReference())
Agreed, I have updated this method for now. I think as a separate PR I may do some refactor work around the rest of the API services to tidy up other areas as I think there's other areas of duplication which could be improved.

2025-01-09 13:20 UTC, JamieBriggs-MoJ commented on build.gradle
> +	implementation 'uk.gov.laa.ccms.data:data-api:0.0.27-398d49f-SNAPSHOT'
Updated to `0.0.29`

2025-01-09 13:23 UTC, JamieBriggs-MoJ commented on src/main/resources/templates/notifications/actions-and-notifications-search.html
> +      <span class="govuk-caption-l" th:text="#{client.notifications.search.subHeading}">Search for notifications</span>
I was playing around with this, and decided it's probably better (and cleaner) to just keep it removed as suggested. My initial thought process was to keep some text there to give context as to what text to expect in the element, then I did think about having some abstract text there to clean. In the end however (and retrospectively thinking), a good IDE would mention what the contents of these message codes anyways so it's best to just have it removed like you said to keep things clean.

2025-01-09 21:02 UTC, arunkumar461 approved these changes

2025-01-10 10:25 UTC, merged