Task/ccls 1771 refactor services
ministryofjustice/laa-ccms-caab pull request #46
Opened 2023-09-08 10:59 UTC by porritta

2023-09-08 11:19 UTC, PhilDigitalJustice commented on src/main/java/uk/gov/laa/ccms/caab/service/CommonLookupService.java
Javadoc on the public methods? Surprised that doesn't get flagged by check style

2023-09-08 11:21 UTC, PhilDigitalJustice commented on src/test/java/uk/gov/laa/ccms/caab/service/CaabApiServiceTest.java
Remove this file

2023-09-08 11:22 UTC, PhilDigitalJustice commented on src/test/java/uk/gov/laa/ccms/caab/service/DataServiceTest.java
remove this file

2023-09-08 11:22 UTC, PhilDigitalJustice commented on src/test/java/uk/gov/laa/ccms/caab/service/SoaGatewayServiceTest.java
remove this file

2023-09-08 11:24 UTC, PhilDigitalJustice requested changes
A few changes, but the rest LGTM

2023-09-08 11:24 UTC, PhilDigitalJustice commented
Dependant on: https://github.com/ministryofjustice/laa-ccms-caab-helm-charts/pull/4

2023-09-08 13:16 UTC, porritta commented on src/main/java/uk/gov/laa/ccms/caab/service/CommonLookupService.java
It's because they are only 1 line methods:

    <module name="MissingJavadocMethod">
      <property name="scope" value="public"/>
      <property name="minLineCount" value="2"/>

2023-09-08 13:16 UTC, porritta commented on src/main/java/uk/gov/laa/ccms/caab/service/CommonLookupService.java
But I will add javadoc anyway

2023-09-08 16:02 UTC, porritta commented on src/main/java/uk/gov/laa/ccms/caab/service/CommonLookupService.java
added

2023-09-08 16:02 UTC, porritta commented on src/test/java/uk/gov/laa/ccms/caab/service/CaabApiServiceTest.java
Replaced with equivalent business service unit tests

2023-09-08 16:02 UTC, porritta commented on src/test/java/uk/gov/laa/ccms/caab/service/DataServiceTest.java
Replaced with equivalent business service unit tests

2023-09-08 16:02 UTC, porritta commented on src/test/java/uk/gov/laa/ccms/caab/service/SoaGatewayServiceTest.java
Replaced with equivalent business service unit tests

2023-09-11 09:47 UTC, PhilDigitalJustice approved these changes

2023-09-11 09:48 UTC, merged